'use client'
import { useEffect, useState } from 'react'
import { Sidebar } from '@/components/sidebar'
import { Header } from '@/components/header'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { toast } from 'sonner'
import { notifyUpdated } from '@/lib/feedback'
const groups=[{kind:'reward',table:'rewards',title:'Rewards',fields:[['name','Name','text'],['description','Description','text'],['point_cost','Point cost','number'],['minimum_level','Minimum level','number'],['minimum_discipline_score','Minimum discipline (%)','number'],['cooldown_hours','Cooldown (hours)','number'],['max_redemptions_per_week','Weekly limit (empty = unlimited)','number']]},{kind:'penalty',table:'penalty_definitions',title:'Penalty rules',fields:[['name','Name','text'],['description','Description','text'],['trigger_points','Activation points','number'],['xp_loss_if_missed','XP lost if expired','number'],['due_in_hours','Time to complete (hours)','number']]},{kind:'category',table:'quest_categories',title:'Categories',fields:[['name','Name','text'],['description','Description','text'],['color','Color','color'],['order_index','Display order','number']]},{kind:'progression',table:'rank_progression_rules',title:'Rank progression',fields:[['from_rank_id','From rank','rank'],['to_rank_id','To rank','rank'],['required_level','Required level','number']]}]
export default function Manage(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[reload,setReload]=useState(0),[editing,setEditing]=useState<any>(null),[values,setValues]=useState<any>({}),[busy,setBusy]=useState(false)
 useEffect(()=>{let active=true;fetch('/api/manage').then(async r=>{if(!r.ok)throw Error('Could not load your settings');const d=await r.json();if(active){setData(d);setError('')}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[reload])
 const save=async(kind:string,id:string,archive=false)=>{if(archive&&!confirm('Archive this item? Past history will be preserved.'))return;setBusy(true);try{const res=await fetch('/api/manage',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,id,...(archive?{archive:true}:{values})})});const result=await res.json();if(!res.ok)throw Error(result.error);notifyUpdated(archive?'Item archived':'Changes saved');setEditing(null);setReload(v=>v+1)}catch(e){toast.error(e instanceof Error?e.message:'Could not save')}finally{setBusy(false)}}
 return <div className="min-h-screen"><Sidebar/><div className="md:ml-64"><Header/><main className="max-w-5xl mx-auto p-4 md:p-8"><h1 className="text-3xl font-bold">Your system, your rules</h1><p className="text-muted-foreground mt-2 mb-8">Fine-tune your rewards and rules. Changes apply to future actions; recorded history is preserved.</p>{error?<div role="alert">{error}<Button className="ml-4" onClick={()=>setReload(v=>v+1)}>Retry</Button></div>:!data?<p role="status">Loading…</p>:groups.map(g=><section key={g.kind} className="mb-8"><h2 className="text-xl font-semibold mb-4">{g.title}</h2><div className="grid gap-3">{(data[g.table]||[]).filter((r:any)=>!r.archived_at&&r.is_active!==false).map((r:any)=><Card key={r.id} className="p-4 flex flex-wrap items-center gap-4"><div className="flex-1"><h3 className="font-semibold">{r.name||`${data.rank_definitions.find((d:any)=>d.id===r.from_rank_id)?.code||'Starting rank'} to ${data.rank_definitions.find((d:any)=>d.id===r.to_rank_id)?.code||'Rank'}`}</h3><p className="text-sm text-muted-foreground">{r.description||'Customize the details to suit your routine.'}</p></div><Button variant="outline" onClick={()=>{setEditing({...g,id:r.id});setValues(Object.fromEntries(g.fields.map(([key,,type])=>[key,r[key]??(type==='number'?null:'')])));}}>Edit</Button><Button variant="ghost" disabled={busy} onClick={()=>save(g.kind,r.id,true)}>Archive</Button></Card>)}{!(data[g.table]||[]).length&&<p className="text-muted-foreground text-sm">Nothing here yet. Create one from its main page.</p>}</div></section>)}</main></div><Dialog open={Boolean(editing)} onOpenChange={v=>{if(!v)setEditing(null)}}><DialogContent className="max-h-[85vh] overflow-auto"><DialogHeader><DialogTitle>Edit {editing?.title}</DialogTitle></DialogHeader>{editing?.fields.map(([key,label,type]:string[])=><div key={key} className="space-y-2"><Label htmlFor={key}>{label}</Label>{type==='rank'?<select id={key} className="w-full rounded-lg border border-border bg-card p-2" value={values[key]||''} onChange={e=>setValues({...values,[key]:e.target.value||null})}><option value="">Starting rank</option>{data.rank_definitions.map((r:any)=><option key={r.id} value={r.id}>{r.name}</option>)}</select>:<Input id={key} type={type} value={values[key]??''} onChange={e=>setValues({...values,[key]:type==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value})}/>}</div>)}<Button disabled={busy} onClick={()=>save(editing.kind,editing.id)}>{busy?'Saving…':'Save changes'}</Button></DialogContent></Dialog></div>
}
