'use client'
import { useState } from 'react'
import { usePathname } from 'next/navigation'
import { LayoutDashboard, Calendar, Zap, Gift, AlertTriangle, TrendingUp, Settings, Menu, X, History } from 'lucide-react'
import { useUser } from '@/components/user-context'
import Link from 'next/link'
import { useIsMobile } from '@/hooks/use-mobile'
const items=[{icon:LayoutDashboard,label:'Today',href:'/system-panel'},{icon:Zap,label:'Quests',href:'/quests'},{icon:Calendar,label:'Calendar',href:'/calendar'},{icon:Gift,label:'Rewards',href:'/rewards'},{icon:AlertTriangle,label:'Penalties',href:'/penalties'},{icon:TrendingUp,label:'Progress',href:'/progress'},{icon:History,label:'Activity',href:'/activity'},{icon:Settings,label:'Settings',href:'/settings'}]
export function Sidebar(){
 const isMobile=useIsMobile(); const [open,setOpen]=useState(false),{user}=useUser(),path=usePathname()
 return <><button type="button" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} aria-controls="main-navigation" onClick={()=>setOpen(v=>!v)} className="fixed top-5 left-4 z-50 md:hidden p-2.5 rounded-xl bg-card border border-border">{open?<X size={20}/>:<Menu size={20}/>}</button><aside inert={isMobile&&!open} aria-hidden={isMobile&&!open?true:undefined} id="main-navigation" className={`fixed inset-y-0 left-0 w-64 bg-sidebar/95 backdrop-blur-xl border-r border-sidebar-border z-40 flex flex-col transition-transform duration-300 ${open?'translate-x-0':'-translate-x-full md:translate-x-0'}`}><Link href="/system-panel" className="p-7 flex gap-3 items-center border-b border-sidebar-border"><div className="p-2.5 rounded-xl bg-primary/15 text-primary"><Zap size={22}/></div><div><span className="text-xl font-semibold tracking-tight">Discipline</span><p className="text-xs text-muted-foreground mt-0.5">Small steps. Real progress.</p></div></Link><nav aria-label="Main navigation" className="flex-1 p-4 overflow-y-auto"><p className="px-3 mt-3 mb-4 text-[10px] uppercase tracking-[0.18em] font-semibold text-muted-foreground">Your workspace</p><ul className="space-y-1.5">{items.map(item=>{const Icon=item.icon,active=path===item.href||item.href==='/settings'&&['/manage','/series'].includes(path);return <li key={item.href}><Link href={item.href} aria-current={active?'page':undefined} onClick={()=>setOpen(false)} className={`flex items-center gap-3 px-3 py-3 rounded-xl text-sm font-medium transition-colors ${active?'bg-primary/12 text-primary border border-primary/20':'text-muted-foreground hover:bg-muted/20 hover:text-foreground border border-transparent'}`}><Icon size={18}/>{item.label}{active&&<span className="ml-auto w-1.5 h-1.5 rounded-full bg-primary"/>}</Link></li>})}</ul></nav><div className="p-4 border-t border-sidebar-border"><Link href="/settings" className="flex gap-3 items-center p-3 rounded-xl bg-card/60"><div className="w-10 h-10 rounded-full bg-primary/15 text-primary grid place-items-center font-semibold overflow-hidden">{user?.avatar?<img src={user.avatar} alt="" className="w-full h-full object-cover"/>:user?.username?.[0]?.toUpperCase()||'U'}</div><div className="min-w-0"><p className="font-medium text-sm truncate">{user?.username||'Your profile'}</p><p className="text-xs text-muted-foreground mt-1">Level {user?.level||1} · {user?.rank||'F-Rank'}</p></div></Link></div></aside>{open&&<button aria-label="Close navigation" className="fixed inset-0 bg-black/60 backdrop-blur-sm z-30 md:hidden" onClick={()=>setOpen(false)}/>}</>
}
